### ISSUE TITLE
Null results for certain HLA loci

### ISSUE THREAD

**Issue by Jwong684** [deepomicslab/SpecHLA#10]
Hi Shuai,

If I have many WES samples with no results for some HLA-loci using the default parameters for WES.

For example in this tumour - normal matched sample:
tumour:
```
# version: IPD-IMGT/HLA 3.38.0
Sample  HLA_A_1 HLA_A_2 HLA_B_1 HLA_B_2 HLA_C_1 HLA_C_2 HLA_DPA1_1      HLA_DPA1_2      HLA_DPB1_1      HLA_DPB1_2      HLA_DQA1_1      HLA_DQA1_2      HLA_DQB1_1  HLA_DQB1_2      HLA_DRB1_1      HLA_DRB1_2
tumour        A*24:02:01:01   A*24:02:01:01   -       -       -       -       -       -       -       -       -       -       -       -       -       -
```

normal:
```
# version: IPD-IMGT/HLA 3.38.0
Sample  HLA_A_1 HLA_A_2 HLA_B_1 HLA_B_2 HLA_C_1 HLA_C_2 HLA_DPA1_1      HLA_DPA1_2      HLA_DPB1_1      HLA_DPB1_2      HLA_DQA1_1      HLA_DQA1_2      HLA_DQB1_1  HLA_DQB1_2      HLA_DRB1_1      HLA_DRB1_2
normal      A*24:02:01:01   A*24:02:01:01   -       -       -       -       -       -       -       -       -       -       -       -       -       -
```

Would you just interpret the lack of results for the MHC I genes to represent a lack of confidence in that locus? Or would you interpret this as a loss of MHC I? The logs don't seem to indicate anything particularly wrong.

**Comment by wshuai294** [comment]
Hello,

The lack of typing results represents a lack of confidence in that locus. Please check the corresponding `hla.allele.*.HLA_*.fasta` file of that locus, the `fasta` file should contain many 'N's caused by the low sequencing depth, making it fail to map to any allele in the database. We only report the LOH event in the `merge.hla.copy.txt` after performing `cal.hla.copy.pl`.

Thank you for pointing this out, we will clarify this in the log and documentation.

Shuai
